-- Trend Delivery - Supabase schema
create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  phone text,
  role text not null default 'employee' check (role in ('admin','manager','dispatcher','employee','driver')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  customer_phone text,
  address text,
  status text not null default 'new',
  driver_id uuid references profiles(id),
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists messages (
  id bigint generated by default as identity primary key,
  from_id uuid references profiles(id),
  to_id uuid references profiles(id),
  order_id bigint references orders(id) on delete set null,
  text text not null,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create table if not exists driver_locations (
  driver_id uuid primary key references profiles(id) on delete cascade,
  lat double precision not null,
  lng double precision not null,
  accuracy double precision,
  updated_at timestamptz not null default now()
);

create index if not exists messages_order_idx on messages(order_id, created_at);
create index if not exists orders_driver_idx on orders(driver_id, status);
